import {useState} from 'react';
const d={nome:'Fazenda Sao Joao',proprietario:'Gustavo',local:'Mato Grosso, BR',area:'450 hectares',plantios:[{cultura:'Soja',area:'200 ha',status:'Crescendo'},{cultura:'Milho',area:'150 ha',status:'Colheita'},{cultura:'Algodao',area:'100 ha',status:'Plantado'}],financeiro:[{mes:'Janeiro',receita:45000,despesa:28000,categoria:'Venda Soja',tipo:'receita'},{mes:'Fevereiro',receita:38000,despesa:32000,categoria:'Insumos',tipo:'despesa'},{mes:'Marco',receita:62000,despesa:25000,categoria:'Venda Milho',tipo:'receita'},{mes:'Abril',receita:29000,despesa:41000,categoria:'Maquinario',tipo:'despesa'},{mes:'Maio',receita:75000,despesa:30000,categoria:'Venda Soja',tipo:'receita'},{mes:'Junho',receita:55000,despesa:27000,categoria:'Venda Algodao',tipo:'receita'},{mes:'Julho',receita:48000,despesa:35000,categoria:'Insumos',tipo:'despesa'},{mes:'Agosto',receita:90000,despesa:22000,categoria:'Venda Milho',tipo:'receita'},{mes:'Setembro',receita:67000,despesa:38000,categoria:'Mao de Obra',tipo:'despesa'},{mes:'Outubro',receita:83000,despesa:29000,categoria:'Venda Soja',tipo:'receita'},{mes:'Novembro',receita:71000,despesa:33000,categoria:'Venda Algodao',tipo:'receita'},{mes:'Dezembro',receita:95000,despesa:45000,categoria:'Venda Milho',tipo:'receita'}],alertas:[{tipo:'warning',msg:'Irrigacao em 2h'},{tipo:'info',msg:'Chuva amanha: 18mm'},{tipo:'success',msg:'Colheita favoravel'}]};
export default function App(){
const [logado,setLogado]=useState(false);
const [email,setEmail]=useState('');
const [senha,setSenha]=useState('');
const [secao,setSecao]=useState('dashboard');
const [fMes,setFMes]=useState('Todos');
const [fTipo,setFTipo]=useState('Todos');
const menu=[{id:'dashboard',label:'Dashboard'},{id:'plantios',label:'Plantios'},{id:'financeiro',label:'Financeiro'},{id:'alertas',label:'Alertas'},{id:'fazenda',label:'Minha Fazenda'}];
const fin=d.financeiro.filter(m=>(fMes==='Todos'||m.mes===fMes)&&(fTipo==='Todos'||m.tipo===fTipo));
const tR=fin.reduce((s,m)=>s+m.receita,0),tD=fin.reduce((s,m)=>s+m.despesa,0),luc=tR-tD;
const fmt=(v)=>'R$ '+v.toLocaleString('pt-BR');
if(!logado)return(<div className="login-bg"><div className="login-box"><div className="login-logo"><h1>AgroDigital</h1><p>Gestao inteligente do campo</p></div><div className="login-form"><label>Email</label><input type="email" placeholder="fazenda@agrodigital.com" value={email} onChange={e=>setEmail(e.target.value)}/><label>Senha</label><input type="password" placeholder="••••••••" value={senha} onChange={e=>setSenha(e.target.value)}/><button className="btn-login" onClick={()=>{if(email==='fazenda@agrodigital.com'&&senha==='123456')setLogado(true)}}>Entrar</button><p className="login-hint">Demo: fazenda@agrodigital.com / 123456</p></div></div></div>);
return(<div className="app-layout"><aside className="sidebar aberto"><div className="sidebar-header"><span className="logo-texto">AgroDigital</span></div><nav className="sidebar-nav">{menu.map(m=>(<button key={m.id} className={"nav-item "+(secao===m.id?"ativo":"")} onClick={()=>setSecao(m.id)}>{m.label}</button>))}</nav></aside><main className="main-content"><header className="topbar"><h2 className="topbar-titulo">{menu.find(m=>m.id===secao).label}</h2><p className="topbar-sub">{d.nome} - {d.local}</p><div className="topbar-usuario">{d.proprietario}</div></header><div className="conteudo">
{secao==='dashboard'&&(<div className="secao"><div className="dash-grid"><div className="dash-card-grande"><h3 className="dash-titulo">Receitas vs Despesas 2024</h3><div className="grafico-barras">{d.financeiro.map((m,i)=>{const maxVal=Math.max(...d.financeiro.map(x=>Math.max(x.receita,x.despesa)));const hR=Math.round((m.receita/maxVal)*140);const hD=Math.round((m.despesa/maxVal)*140);return(<div key={i} className="barra-grupo"><div className="barras-wrap"><div className="barra-receita" style={{height:hR+"px"}}></div><div className="barra-despesa" style={{height:hD+"px"}}></div></div><span className="barra-label">{m.mes.slice(0,3)}</span></div>);})}</div><div className="grafico-legenda"><span className="leg-receita">Receitas</span><span className="leg-despesa">Despesas</span></div></div><div className="dash-col-direita"><div className="dash-kpi-card kpi-verde"><div><p className="kpi-label">Lucro Acumulado</p><strong className="kpi-valor">{fmt(luc)}</strong></div></div><div className="dash-kpi-card kpi-azul"><div><p className="kpi-label">Total Receitas</p><strong className="kpi-valor">{fmt(tR)}</strong></div></div><div className="dash-kpi-card kpi-vermelho"><div><p className="kpi-label">Total Despesas</p><strong className="kpi-valor">{fmt(tD)}</strong></div></div><div className="dash-kpi-card kpi-roxo"><div><p className="kpi-label">Margem</p><strong className="kpi-valor">{tR>0?((luc/tR)*100).toFixed(1):0}%</strong></div></div></div></div><div className="dash-grid-bottom"><div className="dash-card-medio"><h3 className="dash-titulo">Status dos Plantios</h3><div className="plantio-status-grid">{[["Crescendo","#22c55e"],["Colheita","#f59e0b"],["Plantado","#3b82f6"]].map(([st,cor])=>{const qt=d.plantios.filter(p=>p.status===st).length;const pct=Math.round((qt/d.plantios.length)*100);return(<div key={st} className="plantio-status-item"><div className="ps-topo"><span style={{color:cor}}>*</span><span className="ps-label">{st}</span><strong className="ps-qt">{qt}</strong></div><div className="ps-barra-bg"><div className="ps-barra-fill" style={{width:pct+"%",background:cor}}></div></div></div>);})}</div></div><div className="dash-card-medio"><h3 className="dash-titulo">Culturas</h3><div className="culturas-lista">{[...new Set(d.plantios.map(p=>p.cultura))].map(c=>{const total=d.plantios.filter(x=>x.cultura===c).reduce((s,x)=>s+x.area,0);return(<div key={c} className="cultura-item"><span className="cultura-nome">{c}</span><span className="cultura-area">{total} ha</span></div>);})}</div></div><div className="dash-card-medio"><h3 className="dash-titulo">Alertas</h3><div className="alertas-lista">{d.alertas.map((a,i)=>(<div key={i} className={"alerta-mini alerta-"+a.tipo}><span className="alerta-mini-dot"></span><p className="alerta-mini-msg">{a.msg}</p></div>))}</div></div></div></div>)}
{secao==='plantios'&&(<div className="secao"><div className="painel"><h3>Plantios</h3><table className="tabela"><thead><tr><th>Cultura</th><th>Area</th><th>Status</th></tr></thead><tbody>{d.plantios.map((p,i)=>(<tr key={i}><td>{p.cultura}</td><td>{p.area}</td><td>{p.status}</td></tr>))}</tbody></table></div></div>)}
{secao==='financeiro'&&(<div className="secao"><div className="fin-cards"><div className="fin-card fin-receita"><p className="fin-card-label">Total Receitas</p><strong className="fin-card-valor">{fmt(tR)}</strong></div><div className="fin-card fin-despesa"><p className="fin-card-label">Total Despesas</p><strong className="fin-card-valor">{fmt(tD)}</strong></div><div className={"fin-card "+(luc>=0?"fin-lucro":"fin-prejuizo")}><p className="fin-card-label">Lucro Liquido</p><strong className="fin-card-valor">{fmt(luc)}</strong></div><div className="fin-card fin-margem"><p className="fin-card-label">Margem</p><strong className="fin-card-valor">{tR>0?((luc/tR)*100).toFixed(1):0}%</strong></div></div><div className="painel"><div className="fin-filtros"><div className="fin-filtro-grupo"><label>Mes</label><select value={fMes} onChange={e=>setFMes(e.target.value)}><option>Todos</option>{d.financeiro.map(m=>(<option key={m.mes}>{m.mes}</option>))}</select></div><div className="fin-filtro-grupo"><label>Tipo</label><select value={fTipo} onChange={e=>setFTipo(e.target.value)}><option>Todos</option><option value="receita">Receita</option><option value="despesa">Despesa</option></select></div><button className="btn-limpar" onClick={()=>{setFMes("Todos");setFTipo("Todos")}}>Limpar</button></div><table className="tabela"><thead><tr><th>Mes</th><th>Categoria</th><th>Receita</th><th>Despesa</th><th>Saldo</th><th>Status</th></tr></thead><tbody>{fin.map((m,i)=>{const s=m.receita-m.despesa;return(<tr key={i}><td><strong>{m.mes}</strong></td><td>{m.categoria}</td><td className="verde">{fmt(m.receita)}</td><td className="vermelho">{fmt(m.despesa)}</td><td className={s>=0?"verde":"vermelho"}><strong>{fmt(s)}</strong></td><td><span className={"badge "+(s>=0?"badge-positivo":"badge-negativo")}>{s>=0?"Positivo":"Negativo"}</span></td></tr>);})}</tbody><tfoot><tr className="tabela-total"><td colSpan={2}><strong>TOTAL</strong></td><td className="verde"><strong>{fmt(tR)}</strong></td><td className="vermelho"><strong>{fmt(tD)}</strong></td><td className={luc>=0?"verde":"vermelho"}><strong>{fmt(luc)}</strong></td><td><span className={"badge "+(luc>=0?"badge-positivo":"badge-negativo")}>{luc>=0?"Lucro":"Prejuizo"}</span></td></tr></tfoot></table></div></div>)}
{secao==='alertas'&&(<div className="secao"><div className="painel"><h3>Alertas</h3>{d.alertas.map((a,i)=>(<div key={i} className={"alerta alerta-"+a.tipo}><p>{a.msg}</p></div>))}</div></div>)}
{secao==='fazenda'&&(<div className="secao"><div className="painel"><h3>Dados da Fazenda</h3><div className="fazenda-info"><div className="info-row"><span>Nome</span><strong>{d.nome}</strong></div><div className="info-row"><span>Proprietario</span><strong>{d.proprietario}</strong></div><div className="info-row"><span>Area</span><strong>{d.area}</strong></div><div className="info-row"><span>Local</span><strong>{d.local}</strong></div></div></div></div>)}
</div></main></div>);}